// <?php 
//     $Name = #Name;
// ?>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            Une histoire qui casse la routine !
        </title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="style.css"/>
    </head>
    <body id="home">
        <main>
            <section>
                <h2> Est-ce bien toi le "héro" du jour ? <br> Quel est ton petit nom ? </h2>
                    <form method="get" action="PageChoix1.phtml" id="NameForm">
                            <input type="text" name="Name" id="Name" />
                            <input type="submit" id="startBtn" value="Allez, viens je t'emmène !"/>
                    </form>
                </div>
            </section>
            <section>
                <section>
                    <img src="assets/img/cross-swords.png" />
                    <h1>Adieu l'ennui !</h1>
                </section>
            </section>
        </main>
        <script type="application/javascript" src="assets/js/index.js"></script>
    </body>
</html>